dist: xenial
language: python
python:
  - "3.7"
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
script: pytest --cov-report term --cov=src/ --ignore=src/
after_success:
  - coveralls