dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
script: pytest --cov-report term --cov=src/
after_success:
  - coveralls