configuration:
    type: object
    required:
        - task_configurations
        - categories
    properties:
        task_configurations:
            type: array
            items:
                $ref: '#/task_configuration'
        categories:
            type: array
            items:
                $ref: '#/category'
            
task_configuration:
    type: object
    required:
        - type
        - enabled
    properties:
        type:
            type: string
            enum: [cosine_similarity, euclidean_similarity, cosine_neighborhood, euclidean_neighborhood, cosine_outlier_detection, euclidean_outlier_detection]
        enabled:
            type: boolean            

category:
    type: object
    required:
        - name
        - enabled
        - entities
        - tasks
        - categories
    properties:
        name:
            type: string
        enabled:
            type: boolean
        entities:
            type: string
            description: Path to file, which contains all linked entities, which are used to calculate the base noise for tasks.
        tasks:
            type: array
            items:
                $ref: '#/task'
        categories:
            type: array
            items:
                $ref: '#/category'

task:
    type: object
    required:
        - name
        - type
        - test_set
    properties:
        name:
            type: string
        type:
            type: string
            enum: [cosine_similarity, euclidean_similarity, cosine_neighborhood, euclidean_neighborhood, cosine_outlier_detection, euclidean_outlier_detection]
        test_set:
            type: string
            description: Path to local test-set file.